GET  http://localhost:3000/books
authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpYXQiOjE3MDExODg2NTh9.r9QannHtSXNwbeTHvboR2P-QNU9fowpdxguyXgKLHzs

###

POST http://localhost:4000/login
Content-Type: application/json

{
  "userName" : "dlash"
}